const db=require('../config/database')
async function getBooks(req,res){
  try{  
    const [result]= await db.query('select * from books')
    // Return 200 status. The results array is wrapped in an object 
        // with the 'books' key for consistent API structure.
       res.status(200).json({books:result});}
    catch(error){
       res.status(500).json({message:'server error',error: error.message})
    }
}
async function saveBooks(req,res){
try{    
  const {title,author,published_year}=req.body
  //validate if the required inputs were provided
  if (!title || !author) {
            return res.status(400).json({ message: 'Title and Author are required to add a book.' });
        }
        //if published year weren't provided we used null for its value
        // which prevents the database from rejecting our field when we dont provide value
    const[result]=await db.query(`insert into books (title,author,published_year) 
                                              values(?,?,?)`,
                                 [title,author,published_year||null]);
    res.status(201).json({
    message:"book saved successfully",
    book_id: result.insertId //the id generated by the database autocinrement
    });
  }
  catch(error){
    //Catch any database or server execution errors.
    res.status(500).json({message:'server error',error: error.message})
  }
} 
async function deleteBooks(req,res){
try{  
  console.log('Delete ID:', req.params.id);
const id=req.params.id
if (!id) {
            return res.status(400).json({ message: 'Book ID is required for deletion.' });
        }
const [result]=await db.query('delete from books where book_id=?',[id]);
if(result.affectedRows>0){
    res.status(200).json({message:"book removed succesfully"})
}
else{
  res.status(404).json({message:"failed to delete book"})
}
 }
catch(error){
  // Handle Foreign Key Constraint Violation (e.g., Book has active loans in 'loans' table).
  // The error code ER_ROW_IS_REFERENCED is specific to MySQL and indicates related records exist.
  if (error.code && error.code.startsWith('ER_ROW_IS_REFERENCED')) {
            return res.status(400).json({ 
                message: 'Cannot delete book: One or more active loans or records are associated with this book.', 
                error: error.message 
            });
        }
        // Handle all other unhandled server/database errors.
    res.status(500).json({message:'server error',error: error.message})
  }
}
async function updateBooks(req, res){
try{    
  const id = req.params.id;
    const updates = req.body;
    if (!id || Object.keys(updates).length === 0) {
            return res.status(400).json({ message: 'Book ID and update data are required.' });
        }
        const cleanedUpdates = {};
        for (const [key, value] of Object.entries(updates)) {
            // Converts empty string/undefined to SQL-safe NULL
            cleanedUpdates[key] = (value === "" || value === undefined) ? null : value;
        }
    // Build SET clause dynamically
    const setClause = Object.keys(cleanedUpdates).map(key => `${key} = ?`).join(', ');
    const values = Object.values(cleanedUpdates);
    values.push(id);

    const [result] = await db.query(
        `UPDATE books SET ${setClause} WHERE book_id = ?`,
        values
    );
if(result.affectedRows>0){
    res.status(200).json({message:"update succesfully added"})
}
else{
res.status(404).json({ message: "Book ID not found or no new changes were provided." });
}
  }
catch(error){
    res.status(500).json({message:'server error',error: error.message})
  }
}
async function searchBooks(req, res) {
try{  
  const { search, available } = req.query;
 // Initialize the base query. 'WHERE 1=1' allows for easy, conditional addition 
        // of subsequent 'AND' clauses without complex initial checks.
  let query = 'SELECT * FROM books WHERE 1=1';
  let params = [];
  //filter for title and/or author
  if (search) {
    query += ' AND (title LIKE ? OR author LIKE ?)';
    params.push(`%${search}%`, `%${search}%`);
  }
  //filter for availabilty
  if (available) {
    query += ' AND available = ?';
    params.push(available === 'true');
  }
  const [result] = await db.query(query, params);
    res.json({books:result});
  }
  catch(error){
    //internal error
    res.status(500).json({message:'server error',error: error.message})
  }
}

async function getBookStats(req, res) {
  try{
    const [result] = await db.query('SELECT COUNT(*) as total, SUM(available) as available FROM books');
  res.json(result[0]);
}
catch(error){
  res.status(500).json({ 
  message: 'Server error while fetching member statistics.', 
  error: error.message 
  });
}
}

module.exports= {
  getBooks,
  saveBooks,
  deleteBooks,
  updateBooks,
  getBookStats,
  searchBooks
}